Server:
  port: 8081
spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: grishma
    url: jdbc:h2:mem:db_c2c
    driverClassName: org.h2.Driver
    password: password
  jpa:
#    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect